# -*- coding: utf-8 -*-
"""
Created on Mon Jan 11 18:56:54 2021

@author: ferna
"""

import re
import pandas as pd
import json as js
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import confusion_matrix
from sklearn import svm
import pickle
import sys

manchetes = ['anses voucher how to avoid the crowds in the banks to collect the 10,000',
             'the extension of the social bond will cost 23 million the marketers estimates the government',
             'Bonus of 380 soles beneficiaries can withdraw the money at any assigned bank location',
             'is in force mp that allows contract suspension and cut wages',
             'covid 19 force majeure and its potential impacts on petrobras contracts',
             ' alternative drug purchasing arrangements justify raising prices medicaid pays',
             ' african development bank celebrates milestone first social bond listing london stock',
             ' covid 19 crisis afdb celebrates milestone first social bond listing london stock',
             ' afdb celebrates first social bond listing london stock exchange',
             ' alternative drug purchasing arrangements justify raising prices medicaid pays',
             ' eselection 81873 armenian dairy development impact bond terms reference',
             ' pennsylvania halting pay 9000 state workers',
             ' pennsylvania halting pay 9000 state workers',
             ' cost performance based contracting',
             ' african development bank celebrates milestone first social bond listing london stock',
             ' week impact investing essential',
             ' afdb launches record breaking us 3 billion \\ fight covid 19\\ social bond',
             ' eselection 81873 armenian dairy development impact bond terms reference',
             'payment of bonds for quarantine in bolivia creates agglomerations in banks',
             'the impact of economic measures',
             ' west africa wamu releases handbook green bond issues',
             ' uganda benefit sh7 6b afdb corona assistance',
             ' covid 19 crisis afdb celebrates milestone first social bond listing london stock',
             ' african development bank usd 3 bn social bond listed london stock exchange',
             ' african development bank celebrates milestone first social bond listing london stock',
             ' green bond verification market growth overview detailed analysis 2020 2026| det norske',
             ' collaboration license commercial agreements key considerations life sciences',
             ' output vs outcome performance measures',
             'guide to know if you can receive the contingency bonus and how to collect it',
             'second bonus 380 soles in Peru still without a programming date but where and how to collect the',
             ' social impact bonds help government achieve better results families need',
             'public spending as a reflection of government priorities',
             ' social impact bonds help government achieve better results families need',
             ' outlook 2020 meet woman behind fallin wins',
             ' outlook 2020 meet woman behind fallin wins',
             'bono anses reported the schedule to know how many of the more than 11 million',
             'sisben market bonds',
             ' japan student services organization social bond',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' african development bank celebrates first social bond listing london stock exchange',
             ' armenia dairy development impact bond',
             'the government postponed until 2021 the payment of bonds in dollars for usd 10 billion issued',
             ' performance based contracting service level agreements information technology',
             ' afdb lists 3bn social bond lse',
             ' coronavirus – cameroon massive testing campaign launched cameroon',
             ' armenia dairy development impact bond',
             'leganés social services will advise neighbors on rental mortgages and the social bond',
             'eurozone bond chronicle',
             ' afdb lists 3bn social bond lse',
             ' donate uae charities helping affected covid 19',
             ' coronavirus – cameroon massive testing campaign launched cameroon',
             ' donate uae charities helping affected covid 19',
             ' tinsman wrestlemania gives sports leagues blueprint success',
             ' tinsman wrestlemania gives sports leagues blueprint success',
             ' prime therapeutics launches preserverx sm gene therapy financial protection',
             'markets collapse bonds under local law although country risk falls',
             'the 10 thousand peso bonus is consulted on the anses page',
             'Rafael Paz proposes a university support voucher for students from private schools',
             ' buttler amazed success world cup shirt auction',
             ' buttler amazed success world cup shirt auction',
             ' covid 19 afdb lists largest social bond london stock exchange',
             'the council of el rubio eliminates the party of celebrations for socioeconomic aid',
             ' employment bond us',
             ' social impact venture',
             ' africa afdb lists us 3 billion social bond lse',
             'Argentina falls into a new partial default',
             'Córdoba issues a voucher to pay state providers',
             'coronavirus | Anses defined how the process to collect the 10,000 bonus follows',
             ' covid 19 afdb lists largest social bond london stock exchange',
             ' africa afdb lists us 3 billion social bond lse',
             ' afdb debuts london stock exchange largest ever green bond',
             'Paz proposes to create bonds for university students',
             ' results based mental performance plan b',
             ' afdb lists 3bn social bond lse',
             ' afdb debuts london stock exchange largest ever green bond',
             ' social distancing positive impact washington efforts covid 19',
             'the basque government bets on sustainable bonds amid the covid 19 crisis',
             ' coronavirus crisis offers green social bonds chance prove worth',
             ' coronavirus crisis offers green social bonds chance prove worth',
             ' stitched stays poised success coronavirus',
             'investors',
             ' financial inclusion social bond',
             ' social impact funds definition assessment performance',
             ' stitched stays poised success coronavirus',
             'bonds with Argentine legislation sank to 14 after announcement of postponement of payment',
             'consult here independent bond 380 official link to know if you are a beneficiary in the',
             ' prime therapeutics launches solution ease cost burden gene therapy',
             ' covid 19 singapore covid 19 temporary measures bill analysis',
             ' government contracting covid 19 key considerations negotiating new',
             'In the midst of the fall in the collection due to the pandemic, Córdoba issued a bond to be able to',
             'propose bonus for state salaries but quasi-coins',
             'anses voucher 10 000 ife registration form how and where you can collect the subsidy',
             ' rugby union wauchope thunder women team rebuilding following departures grand final',
             ' professor perspectives deploying bridge loans pay success creative responses',
             ' rugby union wauchope thunder women team rebuilding following departures grand final',
             ' professor perspectives deploying bridge loans pay success creative responses',
             'social affairs of the line delivers 143 food stamps for vulnerable families',
             'Ministry of Finance asked to postpone payment of bond interest until August 2020',
             ' andy fearn joins board stafford rangers search continues new manager',
             ' manage brand success work right',
             'thirty years of "public management" in charge',
             'the announced sinking of the grand plan for the hospital',
             'Ecuador asks to defer payment of interest on bondholders',
             'Ecuador requests to defer payment of interest on its external debt in bonds',
             'anses voucher what steps must be followed by those selected to receive the 10,000',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' impact fund india',
             ' ceb issues social inclusion bond response covid 19 pandemic',
             ' afdb us 3bn covid 19 social bond gets lse listing',
             ' coronavirus lasting impact prosperity us fed evans says',
             ' inter american development bank issues 2 billion bond covid relief',
             ' afdb us 3bn covid 19 social bond gets lse listing',
             ' brief jack dorsey impact llc latam covid bond corona tech progress restoration hydro',
             ' go big go home lifesprk scores 16m grow company launch electronic life record',
             ' path breaking software development mantra success sunil sharma hawkscode',
             'government asks to defer payment of interest on bondholders',
             'third bond of 380 soles is it possible after a new extension of the quarantine',
             'the government accounts for the impact on trading companies by the covid',
             ' african development bank ratchets covid relief 10 billion commitment',
             ' brief cdfis action african development bank 10 billion plan home medical exams',
             ' covid 19 worldwide pandemic impact economy markets',
             ' watch buttler amazed success world cup shirt auction',
             ' watch buttler amazed success world cup shirt auction',
             'Ecuador asks to defer payment of interest on bondholders',
             ' african development bank ratchets covid relief 10 billion commitment',
             ' brief cdfis action african development bank 10 billion plan home medical exams',
             ' malawi gvt development bond general information supplement',
             ' contracting authorities act safeguard supplies covid 19 outbreak',
             'automated bond protect platform saturated by "more than a million people"',
             'almost 3 million to mitigate the impact of the coronavirus and cover the regional contribution',
             ' hogan lovells makes training contract offers early cancels summer vacation schemes',
             ' impact bonds working group project pipeline',
             'Ecuador requests creditors to defer payment of interest due to coronavirus',
             'coronavirus impact on contracts and bids',
             ' afdb approves debt deferment private sector clients',
             'the Basque government will issue bonds to stimulate trade, hospitality and tourism',
             'Check here the anses voucher, how do I know if I will receive it and since when will I be able to collect it?',
             'government announces expansion of family protection bond coverage',
             '380 soles voucher, ask if you are a beneficiary of the subsidy',
             'anses bono argentina request denied how to file a claim if selected',
             'he was able to collect the 10 thousand of the ife and incited to loot he was arrested',
             ' social impact disaster ppt',
             ' sports development peace bond world unity says oghomienor',
             ' value based pricing template',
             "Argentina's debt dilemma intersects with the coronavirus and a key decision is approaching", ' designing social impact',
             ' social impact funds definition assessment performance',
             ' covid 19 africa may lose 88bn ― afdb',
             ' talk town alexa chung reveals secret success pay rich people talk',
             ' talk town alexa chung reveals secret success pay rich people talk',
             ' impact british education india',
             ' friendship impacts immune function',
             ' social impact bonds emerging developing countriesle',
             ' social impact bonds emerging developing countriesle',
             ' criminals use names popular social meeting applications distribute cyber threats',
             'figure 8 main actors of a social impact bond',
             ' social impact venture',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' social impact venture',
             "Mayor's Office meets the waterfall of false news", ' russia approved rules “success fee”',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' ravens find value drafting late',
             ' social impact funds definition assessment performance',
             ' social impact venture',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' afdb fight covid 19 social bond listed london stock exchange',
             ' corona bonds europe north south divide',
             ' covid 19 impact states borrow rs 12128 cr bond market lower rates',
             ' largest social bond fight covid 19 afdb launched lse',
             ' afdb fight covid 19 social bond listed london stock exchange',
             ' covid 19 impact states borrow rs 12128 cr bond market lower rates',
             ' ravens find value drafting late',
             ' large integrated us based steel producer signs non binding letter intent niocorp',
             ' teligent management discussion analysis financial condition',
             ' adopt measures mitigate covid 19 impact',
             ' impact fund structure',
             ' payment results social impact bonds outcome based payment systems uk us',
             ' performance based contract types books',
             'municipal buses give transportation bonds red cross',
             'relevance of esg sdg investments in mexico',
             'guide to aid to cope with the coronavirus',
             ' iowa soy farmers paid sustainable soil water outcomes',
             ' iowa soy farmers paid sustainable soil water outcomes',
             ' bihar chief minister nitish kumar asks people stay away covid 19 related rumours',
             'a map teachers messengers and vouchers so that no schoolboy runs out of food',
             'Abu Dhabi Media Office tweet \\ gcc first social impact bond piloted abudhabi',
             ' social impact venture',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             's \\ u0026p places Ecuador in a selective default after the deferral of interest payments on several',
             'the sector asks to be able to administer the bonds on behalf of the client in the gds',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             ' “holy rain” bribes secured ghana work sec alleges',
             ' “holy rain” bribes secured ghana work sec alleges',
             ' managing finances pandemic four step checklist success',
             'anses voucher what can I do if I have cbu to collect the ife',
             'the electricity social bond reaches 17,000 beneficiaries since the state of alarm',
             ' swedish investors lead way surge social bond issuance',
             ' exploring corona crisis bond issuance',
             ' atmah programme increase employment opportunities people determination abu',
             ' exploring corona crisis bond issuance',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             ' swedish investors lead way surge social bond issuance',
             ' atmah programme increase employment opportunities people determination abu',
             ' future returns covid 19 bonds emerge financing tool',
             'Family bonus will be paid first high school students from this Wednesday',
             'financial aid in the US is around $ 1,000 per person while bonds in',
             'The city council of Robledo allocates 155,000 euros to alleviate the economic and social impact on',
             ' social impact bond',
             ' april 2020 impact bond landscape',
             ' “atmah” program increase employment opportunities people determination abu dhabi',
             '[see complete register] solidarity income 160,000 pesos dnp these are the steps you must',
             'the european parliament will support the issuance of bonds in the face of the covid 19 crisis',
             ' april 2020 impact bond landscape',
             'bonds the strategy of world powers to mitigate the economic impact of covid 19',
             'the european parliament will support the issuance of bonds in the face of the coronavirus crisis',
             'the city council of valladolid will allocate 380,000 euros a campaign to promote trade',
             ' new uae initiative help low income coronavirus affected families',
             ' 2 year treasury yield falls 8 year low record drops retail manufacturing',
             ' dalio says investors crazy hold government bonds',
             'bolivia government will allocate up to us 500 million in social bonds for covid 19',
             'caf countries need to adopt “bold public policies” to face the impact of the coronavirus',
             ' argan management discussion analysis financial condition',
             'the worst affected will be the weakest social links',
             'look today covid 19 emergency chile voucher consultation link steps to know the registry',
             'second bonus 380 soles check here on the web how to know if I am a beneficiary in poverty and',
             ' smu students measure monetarily social impact services provided care',
             ' amid pandemic greece issues bond display confidence',
             'bonds anses 10,000 pesos in Argentina, when do the beneficiaries of the',
             'valladolid city council will allocate 380,000 euros a campaign to promote trade',
             ' world bank pandemic bond failure esg shakes virtual agm agendas blackrock green fed fight',
             ' coronavirus daily us death toll hits new high 2492 — happened',
             ' berwickshire housing association secures £5m allia c\\u0026c bond build new homes',
             'government invests more than bs 3 billion in three bonds and guarantees economic stability',
             'media regulator says so far \\ no title has asked for suspension \\',
             'the ucr makes 500 properties available to the government for health care',
             "the pp de moraleja proposes the suspension of the mayor's salary", 'The town hall of Robledo de Chavela allocates 155,000 euros to mitigate the economic impact',
             ' mansfield community development housing director fired',
             ' iadb taps rupiah market sustainable development bond',
             ' social bonds response covid 19 crisis guide issuers',
             ' social bonds response covid 19 crisis guide issuers',
             ' afdb one good term deserves another',
             ' world bank pandemic bond gets black eye amid wave covid relief bonds',
             'executive will deliver a new bond for 760 more than one million rural households',
             'development social impact bonds',
             ' social bonds response covid 19 crisis guide issuers',
             ' berwickshire housing association secures £5m allia c\\u0026c bond build new homes',
             ' coronavirus news bulletin uae 460 new cases confirmed flexible visa schemes offered free',
             ' iadb taps rupiah market sustainable development bond',
             ' covid 19 hit certain indian contracts harder others',
             ' director physician compensation',
             ' social impact bonds emerging developing countriesle',
             ' outcomes based program review closing achievement gaps outside classroom',
             ' kbra releases research – coronavirus covid 19 virus leave lasting',
             ' social bond issuance set grow',
             'the euro chamber supports the issuance of bonds for post-coronavirus reconstruction',
             'rural voucher 760 who will be the beneficiaries of the new subsidy granted by the government',
             'this weekend they will deposit the first 33 thousand bonds protect',
             ' mobilize global testing effort pay success',
             ' mobilize global testing effort pay success',
             ' schlumberger announces first quarter 2020 results',
             ' study carved pharmacy benefits reduce medical costs',
             'voucher covid 19 in chile check with your rut if you are a beneficiary of the state subsidy',
             'Peruvian College of Nutritionists claims bonuses for its professionals',
             ' performance based contracting service level agreements information technology',
             ' covid 19 pay cleaning providers appropriately urge government trade bodies',
             'coronavirus in Argentina only a quarter of those employed are able to work',
             ' trying stay business louisville food truck looks success near interstates',
             'What is behind the return of migrants',
             'voucher covid 19 in chile know the complete guide to access the economic subsidy with rut',
             'see now voucher anses 10 000 Argentine pesos ife when and how can I get paid if I have one',
             ' trying stay business louisville food truck looks success near interstates',
             ' sa considers pandemic responses including 5 3 bn social bond',
             ' south africa considers pandemic responses including 5 3 billion social bond',
             ' govt considering pandemic responses including r100 billion social bond',
             'Brazil despite the political tension and the pandemic, its sovereign bonds continue to price',
             'sustainable finance and green bonds in the Chaco region',
             'voucher 380 what to do if it still appears that my payment is in process',
             ' 10bn covid innovation bonds needed develop mass testing ronald cohen',
             ' video gcc first social impact bond',
             ' depth review change social impact bond',
             ' peterborough social impact bond reduces reoffending 8 4',
             ' homelessness social impact bonds united states',
             ' sa government considers sale r100 billion social impact bond',
             ' south africa considers pandemic responses including 5 3bn social bond',
             ' covid 19 responding business impacts semiconductor bonding equipment market',
             ' maximus results show resiliency face pandemic impact',
             'the ico launches a public issue of social bonds of 500 million to mitigate the impact of',
             'ods1 lilly and its employees help more than 1,700 families affected by the economic impact',
             'issuance of social bonds is doubled',
             '760 family voucher consult the official website of the midis here to find out how to access the subsidy',
             ' el paso isd saves millions refinancing bonds taxpayers benefit',
             'universal bond 380 bond independent bond rural bond See more information about the',
             'learn and teach math with khan academy norte',
             'callaway achieves $ 225 million in bonuses after saving first-quarter profit from',
             'anses bonus what to do if no sms arrived with code to collect ife by nation bank',
             ' richardson isd seeks nominations bond planning committee',
             ' developer proposes bond funding highways',
             ' trending news covid 19 impact metal bond wheel market analysis growth trends',
             'Navarra will promote a pioneering system to finance social innovation at the local level',
             'more than 1,700 families affected by the economic impact of covid 19 will receive aid',
             ' bond finalists bond small ngo impact',
             ' setting success long term retain engage contact center employees fostering',
             ' setting success long term retain engage contact center employees fostering',
             ' maximus results show resiliency face pandemic impact',
             ' 3m wins federal contracts expand us respirator production',
             ' 11 cognitive biases influence political outcomes',
             'learn and teach math with khan academy norte',
             ' book club',
             'a rural uber and cohousing projects to combat depopulation',
             'a rural uber and cohousing among the proposals against depopulation in navarra',
             'ife emergency family income how they can claim those who were rejected for the',
             ' three municipalities guanacaste provide assistance request proteger bond',
             ' boeing ceo coronavirus impact travel 737 max update bond offering',
             'Bilbao will allocate 15 million to cushion the impact of the pandemic',
             'They extend ban on layoffs and will pay two months together of the ife bonus of 10,000',
             ' maximus mms q2 2020 earnings call transcript',
             ' fgl holdings fg q1 2020 earnings call transcript',
             ' lincoln national lnc q1 2020 earnings call transcript',
             '14 measures against depopulation',
             'voucher schedule anses 10 000 ife check here the steps to access the voucher where and',
             'more than two million the impact of covid 19',
             'Universal family bond date on which the link would be published and requirements',
             ' nurses help newborns \\u0026 moms bond',
             ' investing social impact familys guide',
             ' director social impact',
             ' vafa animal shelter',
             'cnv wants to create a solidarity fund for provinces',
             'universal voucher make the consultation on the midis web and steps to access the economic benefit',
             'second voucher 380 soles check with your ID if you are a beneficiary',
             ' new federal rules pave way patient driven health information exchange real',
             'the government creates a system of social impact bonds against depopulation',
             ' covid 19 impact analysis revenue die bonding equipment market continues dip amid',
             ' detail needed avalon park project | view',
             ' research vitrified bond grinding wheels market impact covid 19 top players',
             ' gate zero dana white says ufc 249 success',
             ' legislature setting agency spending limits mandates',
             ' marcus jordan \\ heir\\ michael jordan basketball empire',
             ' accenture positioning success',
             ' legislature setting agency spending limits mandates',
             ' marcus jordan \\ heir\\ michael jordan basketball empire',
             ' accenture positioning success',
             'governance in cis social impact contracts',
             'create new investment in \\ solidarity bonds \\ to fund provinces',
             'Risk rating commission rejects debt instruments from milestones due to the impact of',
             'universal family voucher when will the link to collect the 760 be available know it here',
             ' texas aco adds 100 primary care physicians',
             ' rignet management discussion analysis financial condition results',
             ' citi launches first usd denominated green bond',
             ' kbra releases research – coronavirus covid 19 virus leave lasting social impact',
             ' green bonds bring renewable energy life — portfolio look like',
             ' headinvest llc buys vanguard short term corporate bond etf vanguard short term bond',
             'seek to create a trust to assist the provinces',
             'pami and anses will pay a retired bonus of how much it will be and who will collect it',
             'Arequipa businessmen will deliver solidarity bonds vulnerable families',
             'psoe calls for \\ direct help \\ with vouchers for the most vulnerable people',
             ' benefits outcome based contracting',
             ' performance based contracting',
             ' aiib preps sustainable development bond fund covid 19 response',
             'governance in cis social impact contracts',
             ' report | ufc 249 draws big pay per view numbers amid pandemic',
             'four afp buy debt of the finance ministry for rd 40 billion',
             'endangered species another virus victim adam minter',
             ' new gsg chief wants broaden appeal social bonds amid pand',
             ' impact covid 19 ground bond safety tester market technological trends 2020 2027',
             'the kincardine floating wind farm receives € 417m in financing and the certification will be',
             ' behavioral health payer based strategy improving access quality covid 19',
             ' new risks new rewards new expo',
             ' wexford pho moves sph analytics improved population health manage',
             'Latin America and the Caribbean launch initiative to face the economic impact of the covi',
             ' pandemic spurs investor interest social b',
             ' resin bond blade market size share 2020 development trend key manufactu',
             'evo morales government indebted the country by bs 69 332 million in doubtful projects',
             ' pandemic spurs investor interest social b',
             ' coronavirus butterfly effect six implications sustainable inves',
             ' bonds deliver 562m boost build social housing vulnerable austral',
             'btr sector primed juice',
             'btr sector primed juice',
             'economic revival the new opportunities of hard finance',
             ' prospects green bonds social impact b',
             'social end',
             ' pandemic driven surge social bond issuance shows sustainable debt market evol',
             ' bonds deliver 562m boost build social housing vulnerable austral',
             ' horoscopes june 25 2020 busy philipps market succ',
             ' horoscopes june 25 2020 busy philipps market succ',
             ' social impact data',
             ' social impact bonds help government achieve better results families',
             ' development impact project agreement including provisions job contribution grant',
             ' social impact data',
             ' payment results social impact bonds outcome based payment systems uk',
             ' impact investing lo',
             ' composite adhesives market development forecast 2027 – lord loxeal engineering',
             ' ed yardeni slams fed setting market',
             ' esg funds setting record pace launches',
             ' roll bond evaporator market 2020 covid 19 impact growth kangsheng group jiangsu',
             ' outcomes based program review closing achievement gaps outside classroom',
             ' download performance based contrac',
             ' nrl compete afl sy',
             ' nrl compete afl sy',
             ' social impact bonds help government achieve better results families',
             ' coronavirus pandemic impact roll bond evaporator market growth rate 202',
             ' roll bond evaporator market 2020 covid 19 impact growth kangsheng group jiangsu',
             ' potential impact coronavirus covid 19 nickel bond blades market size share',
             'bpifrance refinances into corporate bonds',
             ' investing social impact familys g',
             ' social impact',
             ' payment results social impact bonds outcome based payment systems uk',
             ' nhfic finalises 562 million social',
             ' impact covid 19 outbreak metal bond grinding wheels market component key players',
             ' impact covid 19 roll bond evaporator market comprehensive growth 2020 2027 top',
             'economy z',
             ' week impact investing repri',
             ' social impact bonds measure progress towards global education',
             ' 6 common sports betting rookie mist',
             ' 6 common sports betting rookie mist',
             ' week impact investing repri',
             ' david adefeso words share mark zuckerberg – check mes',
             ' post',
             ' david adefeso words share mark zuckerberg – check mes',
             ' post',
             '10 000 anses bond analyzes what the third stage of the',
             'Brazilian bonds with worse performance due to high debt bonds l',
             'Brazilian bonds with the worst performance due to high d',
             ' hair bond multiplier market size share global trends key players analysis growth factors',
             ' insight different time—pandemic induced recession drives transfer pricing cha',
             ' say want',
             ' social impact',
             ' download transformations social b',
             ' build values based portfolio according top adv',
             ' download transformations social b',
             'emanuel pinheiro determines that public servants contracts be renewed',
             ' passport anthem protest loss medicaid contracts claiming awards biased un',
             'anses bond in july credits and atp for the amba the economic announcements of alberto ferná',
             ' covid 19 lockdown social impact chil',
             'voucher ife anses who will collect for the third time the 10,000 benef',
             'culture decides to maintain the 250 euro tourist voucher for health professionals',
             'How did the new coronavirus covid 19 impact online casinos in esp',
             ' cost performance based contrac',
             ' caf social impact',
             ' download social f',
             'ife anses de julio how will the third batch of the bonus be and who will collect it',
             'the demands of mos social services increased by 30 with the pand',
             ' theory social impact b',
             ' antecedents social',
             ' impact covid 19 global dog collars market 2020 2027 | bond co good2go 5280 dog',
             'targeted residential users of the electric utility',
             'state aid is delayed while the economic social impact is catastrophic',
             ' impact investing lo',
             ' boxing champion floyd mayweather pay george floyd fun',
             ' polypropylene pp spunbond non woven fabric market development market trends key driven',
             ' shaving lotion market 2020 covid 19 impact prominent players perio taylor old bond',
             ' global dog leash market 2020 – impact covid 19 future growth analysis challenges',
             ' “does things',
             ' “does things',
             ' healthcare holy grail health plan guide succeeding value based care stra',
             ' knowledge based corporations contributing caspian sea oil examination proce',
             'voucher for workers universal family voucher and electricity voucher links for subsi',
             ' social impact bonds emerging developing countri',
             ' negotiating outc',
             ' download outcome fun',
             ' performance based contracting service level agreements information techno',
             ' social impact bonds emerging developing countri',
             ' social policy b',
             ' preconceived notions sustainable invest',
             ' commissioning manager children health outcomes – maternity leave c',
             ' covid 19 effect roll bond evaporator market share development',
             ' stoking passion impact bonds passion social',
             ' esg blog cfrf publishes industry industry guide climate related financial r',
             'Universal voucher 760 where to charge and see if you are a beneficiary of the subs',
             ' payment results social impact bonds outcome based payment systems uk',
             'rural voucher 760 what are the modalities to collect this subsidy from the peruvian government',
             ' stoking passion impact bonds passion social',
             ' covid 19 impact electronics adhesives market development status key players analysis',
             ' global covid 19 impact super hard material market development forecast industry size',
             ' impact covid 19 vehicle mechanical bond radiators global market 2020 latest trends',
             ' stoking passion impact bonds passion social',
             ' opinion | guide proposed social stock exchange',
             ' medicaid vbp rule may facilitate drug contracts questions re',
             ' stoking passion impact bonds passion social',
             ' opinion | guide proposed social stock exchange',
             ' fitch rates nba notes outlook st',
             ' road recovery requires collaborative three part appr',
             ' gtcr cedar gate technologies announce acquisition citra health solut',
             ' esg focus impact join risk return',
             ' infrastructure bonds floated development finance institution could aid quicker reco',
             ' impact investing lo',
             ' social bond sovereign green bond issuance su',
             'aqualia presents \\ listen \\ its sustainability report',
             ' class collective actions radar steps suc',
             ' 2020 health value based pri',
             ' setting success unpredictable w',
             ' setting success unpredictable w',
             ' caf social impact',
             ' impact bonds future sustainable fixed income inves',
             ' multifamily green bond impact report highlights financial social environmental benefits',
             ' large inflows social bond market linked covi',
             'company from Santa Catarina creates a platform for lifecycle management and contract management',
             ' payers continue expand value based contracting despite covi',
             ' gtcr cedar gate technologies announce acquisition citra health solut',
             ' carecentrix expands offerings medicaid plans adds scott markovich general manager',
             ' multifamily green bond impact report highlights financial social environmental benefits',
             ' scope legal support services triggerise kenya ltd',
             ' miss earth sa ambassador advocates sustainable develop',
             ' volvo impact',
             ' widow rayshard brooks delivers emotional impact statement bond hearing ex apd',
             'solidarity income colombia consult here how to apply to the voucher to be a beneficiary of the',
             ' ipo preview ncino rolls plans us',
             ' chainlink link oracles power nft based blockchain games poly',
             ' payment results social impact bonds outcome based payment systems uk',
             ' innovating pay success model social derivati',
             'create impact leads a funding round in',
             ' high bond vhb tape market size share development',
             ' sec urges social bonds support recovery pand',
             ' new gorbals housing association secures funding housing finance corpora',
             'company from Santa Catarina creates a platform for lifecycle management and contract management',
             ' name bond… insert impact term',
             ' look far ve come impact inves',
             ' responsible investing traditional asset c',
             ' payment results social impact bonds outcome based payment systems uk',
             ' look far ve come impact inves',
             ' roll bond evaporator market analysis impact covid 19 growth opportunity',
             ' ethyldiglycol acrylate edga market 2020 covid 19 impact players basf double bond',
             ' polypropylene pp spunbond non woven fabric market | covid 19 impact | cost analysis',
             ' look far ve come impact inves',
             ' isda clause library small step parties giant stride ma',
             ' independence contract drilling inc reports certain operational financial data second',
             ' blood type may affect covid 19 outcomes study',
             'covid 19 stimulates the issuance of social bonds and sustains',
             'caixabank issues a covid 19 social bond for € 1 billion',
             'paramés and león team up with mapfre to launch an imp fund',
             ' social impact funds definition assessment',
             ' payment results social impact bonds outcome based payment systems uk',
             ' social impact bonds emerging developing countri',
             ' setting stage success new financial',
             'ubs launches first criteria-based global corporate bond etf',
             ' setting stage success new financial',
             ' look far ve come impact inves',
             ' name bond… insert impact term',
             ' fannie mae releases report multifamily green b',
             'on',
             ' sustainable financial partnerships sdgs case social impact b',
             ' social impact bonds emerging developing countri',
             ' outcomes based program review closing achievement gap',
             ' performance based contracting military supply chains',
             ' outcomes based program review closing achievement gaps outside classroom',
             ' rare win win win — ascs come pandemic stronger',
             'anses bonus today they begin to collect the ife of 10 000 who already informed the bank account',
             ' bond issuances transparency invest',
             ' korean housing lender issues first covid 19 response social covered',
             ' outsourcing practices changing 2020 industry ins',
             ' social impact bonds emerging developing countri',
             ' social impact bonds help government achieve better results families',
             ' sustainable financial partnerships',
             ' social impact bonds help government achieve better results families',
             ' social impact funds definition assessment perform',
             ' future business contracts post covi',
             ' australian pci construction industry contracts slower pace',
             ' korean housing lender issues first covid 19 response social covered',
             ' islamic social finance entrepreneurship cooperation sharing eco',
             ' pdf payment results social impact bonds',
             ' nfl rumors 49ers raheem mostert requested pay raise offse',
             ' mowi grieg green bond success reveals great potential drive capital salmon',
             'the funds will place up to 1 billion in bonds to buy more m',
             'electricity voucher to pay the electricity bill who are the beneficiaries of the 160',
             ' bond alignment system market size top leading key players growth opportunities [covid 19',
             'norway sustainability is essential in post covi economic recovery',
             ' ronnie ho',
             ' impact investing lo',
             ' public involvement social impact assess',
             ' audit questions cost savings health outcomes onecare ver',
             ' personalize care improve patient heart',
             'beyond bonuses for a social protection system for the',
             ' scottish association secures funding via aggregator first sub 2 bond',
             ' sec encourages social bonds support recovery covid 19 pand',
             ' bond alignment system market size top leading key players growth opportunities [covid 19',
             ' blended finance post covid19 w',
             ' blended finance post covid19 w',
             'universal bond 760 when the new standard for economic subsidy comes out',
             'Banco la hipotecaria sa receives financing from responsability investment',
             'beyond the covid 19 bonds, what about the mental health of people?',
             ' social investments \\u0026 law case alternative investm',
             ' daniel craig felt austin powers films f cked james',
             'investment with social and environmental impact under a new impulse by the pand',
             ' setting business accounting sy',
             ' political party manifestoes social contracts – cdd g',
             ' impact covid 19 bond alignment system market projected grow massively near',
             ' global vitrified bond grinding wheels market 2020 2026 | latest covid19 impact analysis',
             ' outcomes based conditionality role optimal de',
             ' faith social capital debt cr',
             'social bonds take over in sustainable financing with 80 billion emit',
             ' evaluating social funds cross country analysis community investm',
             ' social bond investigation bases law abidingness vol iii safeguards',
             ' information modeling essential housing construct',
             ' outcome based marketing new rules marketing',
             ' performance based management every manager get res',
             ' cms proposed medicaid best price loophole value based purchasing d',
             ' guaranteeing development impact financial guarantees development centre stud',
             ' social impact arts intellectual',
             ' social europe impact single market womens employment textile industry',
             ' dougundp tweet \\ first ever social impact bond hiv services london supported',
             ' cms proposed medicaid best price loophole value based purchasing d',
             ' parsons awarded 178m intelligence cont',
             ' infrastructure companies must embrace data digital disrup',
             ' performance based contracts road projects comparative analysis different',
             ' performance based contracting roadway maintenance operations ind',
             'asbama and its affiliates donate 1,050 market bonds in magda',
             'virtual boarding school of social impact in v2a consul',
             ' three quarters parents developed closer bond children lock',
             ' global resinoid bond grinding wheels market 2020 future development – klingspor tyrolit',
             ' privatization social impact social safety',
             ' covid 19 impact roll bond evaporator market | strategic industry evolutionary analysis focus',
             ' alumina dbc direct bond copper substrate market size share development',
             ' global passive digitizer market 2020 covid 19 impact analysis – development factors',
             ' big issue joins elton john world first social impact bond combat',
             ' ipo launch ncino proposes terms 175 million',
             ' download delinquency schools social bond christine',
             'the government guarantees water and electricity until September and will extend the mortgage moratorium',
             'Spain extended its soci shield until the end of September',
             'Banana Association of Magdalena la Guajira and Cesar continue their commitment to the',
             ' download social impact electronic funds tran',
             ' social bonds city',
             ' global cross linked polymers market overview covid 19 impact development key players',
             ' condition barrier success – kaduna cri',
             ' condition barrier success – kaduna cri',
             '\\ Green bonds and Chinese fixed income are sources of value in the face of uncertainty',
             ' world first hiv social impact bond tests 120000 south londo',
             ' june 2020 monthly policy brie',
             ' growing international innovation local ecosystem requires strategic appr',
             ' five things money',
             ' june 2020 monthly policy brie',
             ' industrial revenue bond impact study sharlene shoem',
             ' amideast egypt citi foundation host first virtual skills success gradua',
             ' impact covid 19 roll bond evaporator market 2020 2025 clad metal india pvt ltd talum',
             ' princes risborough school given government cash pay vital maintenance',
             ' amideast egypt citi foundation host first virtual skills success gradua',
             ' dress success transforms lives taur',
             ' province calling expressions interest social impact bond',
             ' green bonds fade social bonds b',
             ' benefits foundations float bonds grant mak',
             ' dress success transforms lives taur',
             ' princes risborough school given government cash pay vital maintenance',
             ' amideast egypt citi foundation host first virtual skills success gradua',
             ' fitch rates major league baseball trust \\u0026 major league baseball facility fund st',
             ' specialty pharmacy divide health systems payers find common gr',
             ' blueprint state leaders achieve better res',
             'the San Carlos bonds are already of course l',
             'udlap proposes plan to reduce the economic impact of coronav',
             'universal voucher 760 what you should know about the government subsidy',
             ' social impact measurement social purpose organizat',
             ' sector',
             ' province calling expressions interest social impact bond reduce youth recidi',
             ' impact investor durreen shahnaz must go beyond social bo',
             ' corona pandemic impact composite adhesives market change development',
             ' coronavirus pandemic impact electronic potting encapsulating market development',
             ' benefits blockchain marketing 2020 – entrepreneurial strategies suc',
             ' benefits blockchain marketing 2020 – entrepreneurial strategies suc',
             ' manitoba looks private sector help reduce youth recidivism social impact',
             ' impact investor durreen shahnaz must go beyond social bo',
             ' bonding film market exploring impact trends strategies key players hitachi',
             'the government corrects its extension of the electricity social bond to extend it only 15',
             'solidarity funds advance cnv project to finance public works',
             ' bonding film market exploring impact trends strategies key players hitachi',
             ' global polypropylene pp spunbond non woven fabric market report 2020 – covering impact',
             ' columbus blue jackets quest suc',
             'sangüesa will host the "repopulation bus" in ag',
             'country issues bonds the highest rate in recent',
             'universal bond 760 all that is known at the moment regarding the second pattern of the subs',
             ' columbus blue jackets quest suc',
             ' pay succ',
             ' pay succ',
             ' july 2020 impact bond lands',
             ' province calling expressions interest social impact',
             ' service payment estima',
             ' could covid 19 convince canadians pay online n',
             ' could covid 19 convince canadians pay online n',
             'Sangüesa and arróniz will host the repopulation bus state tour in August',
             'Contest \\ heroes of the bicentennial \\ launched to improve life in Peru',
             ' service payment estima',
             ' look cms proposed medicaid drug rebate cha',
             ' risky business uncertain outcomes application bankruptcy code',
             ' glass bonding adhesive market 2020 | covid19 impact anal',
             'air service level France will cease its activity and initiate a plan',
             ' west lake hills cancels 22 million infrastructure',
             ' social impact bonds pros',
             ' global wire bonding machine market forecast type application 2021 2026',
             ' results hours productivity measured covi',
             ' manitoba ndp nahanni fontaine said bond system als',
             ' global revolution latin music social im',
             ' social impact bonds pros',
             'It is urgent to transform the economic model of Latin America.',
             ' evaluating social funds cross country analysis community investm',
             ' covered bonds covid french issuers perspec',
             ' global roll bond evaporator market 2020 impact covid 19 future growth analysis',
             ' high bond vhb tape market 2020 research report covers updated data considering',
             'sangüesa and arróniz will host in august the state tour “bus de la repoblac',
             'rural voucher 2020 consultation link rural voucher 760 soles where and how to register how to find out',
             ' elton john aids founda',
             ' website traffic become defining metric success post covid',
             ' website traffic become defining metric success post covid',
             ' agent take patrick mahomes lengthy contract extension likely prove anomalous two big',
             ' development finance china bond market innova',
             'raverta on the ife “managed that around 3 million people fall into poverty',
             'contest of organizations with social impact in search of the heroes of the bicentennial',
             'U.S. stock futures tumble as investors move state bonds',
             ' agent take patrick mahomes lengthy contract extension likely prove anomalous two big',
             ' bbva green bonds reduced carbon footprint 724 000 tons co2',
             ' audit report identified staff failings dealing contr',
             ' clinicians find encouraging results functional mr unresponsive patient covi',
             'third payment of the ife everything you need to know about the 10 anses bonus',
             ' take step back small cap trader shares strategy methods suc',
             'covid 19 marginality and contract',
             ' take step back small cap trader shares strategy methods suc',
             ' download social impact inves',
             'In the absence of a rescue plan, the corporate bonds of Mexico fall',
             ' green bond verification market 2020 | covid19 impact analysis | top companies kpmg trucost',
             ' social stock exchange new funding avenues non profit organisat',
             ' social stock exchange new funding avenues non profit organisat',
             'millionaires invest three out of ten dollars in stocks and b',
             ' indian impact investing comes age raises 11 b capital touches 490 million l',
             ' social stock exchange new funding avenues non profit organisat',
             ' indian impact investing comes age raises 11 b capital touches 490 million l',
             ' lake woods speedway first pay per view event suc',
             ' sftb benefits fowler plays well key success',
             ' sftb benefits fowler plays well key success',
             ' technology procurement challenges smart building developers opera',
             ' social stock exchange new funding avenues non profit organisat',
             ' global bond market status development trend type application future forecast',
             ' global resin bond diamond powder market size share development trend demand industry',
             ' main principles esg inves',
             ' final report study social impact coal development decker birney ashland',
             ' lasting impact global social responsibility cameroon united states america',
             ' bet covid 19 sto',
             ' bet covid 19 sto',
             ' report ufc 251 draws 1 3 million pay per view buys e',
             ' value based care profile equality health actionable data plat',
             ' potential scaling social outcomes contracts – sustainability bonds impact linked re',
             ' download social fin',
             ' bond covenant r david',
             ' ryan girdler paints picture bulldogs path back suc',
             ' ryan girdler paints picture bulldogs path back suc',
             ' implementing outcome based home care workbook obqi care pathways disease',
             ' download public performance based contrac',
             ' social impact bond sib defini',
             ' let discuss social impact bonds',
             ' century housing 100m bond offering sees rapid suc',
             ' covid 19 impact roll bond evaporator market research development top companies',
             ' fitch rates empire state development ny 2 3b personal income tax revs aa outlook',
             ' distribution pattern trends \\u0026 opportunities forecast bond market ongoing',
             'Ife anses bond the government set an expiration date and discusses another subsidy scheme',
             'universal voucher 760 all details of the subsidy for peru',
             'the strong impact on private clinics',
             ' social impact investment building evidence',
             ' future work reimagining virtual collaboration suc',
             ' nei launches impact bond',
             ' debt capital raising covid 19 practical',
             'after the 10,000 bond the government points to a “universal income of b',
             'Green bond issuance in Panama gains international recognition',
             'In the government they think of ways to interrupt the 10,000 bond and transform it into a “rent',
             ' nei introduces first suite impact funds ca',
             ' biden unveils ambitious plan reach 100 clean electricity 2035 pour trillions green en',
             'download contract supplement',
             ' biden proposes plan reach 100 clean electricity',
             ' biden unveils ambitious plan reach 100 clean electricity 2035 pour trillions green en',
             ' biden unveils ambitious plan reach 100 clean electricity 2035 pour trillions green en',
             ' outcomes based health',
             ' outcome versus service based payments health care kenneth lynch leo',
             ' biden unveils ambitious plan reach 100 clean electricity 2035 pour trillions green en',
             'anses ife voucher how to collect the contribution if you received the dé card',
             ' growing number homeless encampments denver alarming neighbors schools fami',
             'social impact micro electronics netherlands advisory group rath',
             ' social economic impacts tuungane final report',
             ' big firm won race taxpayer',
             ' nigeria vote fide',
             ' research resin bond grinding wheels market impact covid 19 2020 2026 dsa products',
             ' nigeria vote fide',
             'the psoe highlights that more than 29,000 people from Córdoba benefit from the electric social bond',
             'henkel first company to close a plastic waste reduction bond',
             ' social impact bonds emerging developing count',
             ' social impact bonds need',
             ' amazon com affectivity social bond transcend',
             ' vote fide',
             ' brief blackrock stewardship shortfall blackstone alt dairy bet kkr green collar forestry',
             ' vote fide',
             ' invest community based organizations put health dollars really ne',
             ' cdc expands list higher covid 19 risks',
             ' performance based contrac',
             'maggi company benefits consumers with rd 3 million in bonds',
             ' social impact bonds emerging developing count',
             ' brief blackrock stewardship shortfall blackstone alt dairy bet kkr green collar forestry',
             ' corona impact acrylate adhesives market segmentation analysis recent trends',
             ' vitrified bond wheel market 2020 research covid 19 impact analysis 2027 – klingspor',
             ' brief blackrock stewardship shortfall blackstone alt dairy bet kkr green collar forestry',
             ' social bonds freedom revisiting dichotomy universal partic',
             ' covid 19 epidemic impact vehicle mechanical bond radiators market see strong growth',
             'aqualia new sustainability report',
             ' launch social stock exchange may mark new chapter impact financing',
             ' launch social stock exchange may mark new chapter impact financing',
             'López asserts that the legislative assembly "is against the',
             ' launch social stock exchange may mark new chapter impact financing',
             ' smfg invest british asset manager eye esg bonds sou',
             ' launch social stock exchange may mark new chapter impact financing',
             ' fan pass launch event written thrive global launched huffington',
             ' fan pass launch event written thrive global launched huffington',
             ' environmental social impact assessment introduc',
             'maggi® will benefit its consumers with more than rd 3 million in gas bonds',
             ' launch social stock exchange may mark new chapter impact financing',
             ' research alumina dbc direct bond copper substrate market impact covid 19 top',
             'high yield bond trader',
             ' microcapital brief african development bank afdb joins nasdaq sustainable bonds',
             ' hair bond multiplier market 2020 | analyzing covid 19 impact followed restraints',
             ' download social impact micro electro',
             'sociology health care john bond scores',
             'timeline of gold as a monet instrument',
             ' microcapital brief african development bank afdb joins nasdaq sustainable bonds',
             ' metal bond wheel market worth observing growth | klingspor 3m m',
             'sociology health care john bond scores',
             ' social bonds ri',
             ' siegfried ruhl esm plans help eurozone coronav',
             ' covid 19 inflection point social inves',
             ' siegfried ruhl esm plans help eurozone coronav',
             'asg of the variable income the fixed and evolution',
             ' social impact b',
             ' nigeria bond lady tackles public debt strat',
             ' global bond alignment system market report 2020 – covering impact covid 19 financial',
             ' nigeria bond lady tackles public debt strat',
             ' global bond alignment system market report 2020 – covering impact covid 19 financial',
             ' week impact investing true co',
             ' social impact bond service provider capabilities due diligence introduc',
             ' performance based contrac',
             ' using pay success criminal justice projects',
             ' central african republic impact evaluation',
             ' development impact bonds',
             ' social impact bond market uk',
             ' rise results based financing education',
             ' social impact bonds encourage targeted investments well agreements drafted parties – public sector investors service providers – benefit',
             ' social financing payment results greater driver efficiency innovation impact tacking social problems',
             ' launched innovative new financing solution social success note',
             ' burnham announces £1 8m bond help homeless',
             ' new development impact bond benefit indigenous people',
             ' ccmua pioneer first kind financing waste energy microgrid city camden',
             ' gov nikki haley launches landmark “pay success” project improve maternal child health increase government accountability',
             ' south carolina launch social impact bond program improve maternal child health mission investors exchange 2013',
             ' story behind world’s first environmental impact bond',
             ' potential limitationsof impact bonds',
             ' impact investment blossoming japan',
             ' saskatchewan children risk care',
             ' los angeles county launched reach jir new health based housing program',
             ' impact bonds developing countries early learnings field',
             ' children need social impact bond',
             ' new social impact bonds support public services',
             ' goldman success social impact bond aids schoolchildren',
             ' restaurant chain pioneered social impact bond fight malaria',
             ' better outcomes better value evolution social impact bonds uk',
             ' victoria’s first social impact bond address homelessness',
             ' pilot ‘social impact bond rendiz’',
             ' social impact bonds made switzerland – finally',
             'launch of social impact bond buzinezzclub eindhoven',
             ' devon launches pioneering outcomes based programme prevent diabetes',
             ' bangladesh primary education development program iii',
             ' burkina faso impact evaluation',
             ' investment plan europe first social impact bond scheme europe supports integration finland',
             ' first kind development impact bond launched cameroon save newborn babies',
             ' martine pinville presents six new projects brink social impact contract',
             ' red cross launches new bond tap private money',
             ' kyrgyz health results based financing',
             ' payment results strategy sharpening incentives perform',
             ' province invites ideas landmark social impact bond',
             ' preventing youth homelessness intensive tailored flexible counselling guidance',
             ' ventura county project support reentry',
             ' bnp paribas expands social impact bond portfolio support veterans new york massachusetts',
             ' burundi impact evaluation',
             ' ghana impact evaluation',
             ' five london boroughs join forces help troubled families stay together',
             ' cali launches second social impact bonds project colombia',
             ' environmental impact bonds financing wetlands restoration',
             ' impact bond global database social finance',
             ' israel’s first social impact bond gets underway social finance israel',
             ' work prison factsheet social impact bond',
             ' bnp paribas announces launch three new social impact bonds france',
             ' social impacts bonds reducing reoffending western australia',
             ' roadmap pay success philadelphia',
             ' first austrian social impact bond economic social empowerment women affected violence juvat',
             ' zimbabwe impact evaluation',
             ' newpin social benefit bond',
             ' big step toward first social impact bond developing world',
             ' zambia impact evaluation',
             ' bnp paribas announces launch three new social impact bonds france',
             ' resolve social benefit bond',
             ' richmond city council approves first nation social impact bond address blighted housing conditions',
             ' social impact bond south carolina case study',
             ' seoul social impact bond sib',
             ' social impact bonds uk',
             ' public private sector partnership prevent suicide',
             ' cuyahoga county partnering family success program',
             ' newpin qld social benefit bond queensland’s first social impact bond',
             ' atlanta department watershed management wins environmental impact bond challenge green infrastructure resilience projects city westside',
             ' investment proposal homeless families social impact investment',
             ' aspire social impact bond aspire sib australia’s first homelessness focused sib',
             ' essential skills social finance project colleges institutes canada',
             ' world’s first cross border social impact bond helps jobseekers enschede find work germany',
             ' lesotho impact evaluation',
             ' israel social impact bond help bedouins maths studies',
             ' village enterprise closes investment first development impact bond poverty alleviation sub saharan africa',
             ' reproductive child health project',
             ' keeping children care',
             ' investing social outcomes development impact bonds',
             ' chad impact evaluation',
             ' csh helps public private philanthropic sectors partner improve housing healthcare',
             ' bridges ventures backs uk first active healthcare sib',
             ' project home awarded support study supportive housing',
             ' growing social investment market',
             ' press release ics announces recipients technical assistance support pay success financing improve early childhood outcomes oklahoma florida',
             ' israel launches first social impact bond prevent type 2 diabetes',
             ' social impact bonds latin america reframing social development region',
             ' new impact investing model education',
             ' social impact contracts signing commitment protocol passeport avenir fight dropping school agricultural education',
             ' alameda county justice restoration project launched',
             ' fusion housing uses multi disciplinary team approach support guidance reduce youth homelessness',
             ' strengthening prevention family assistance programmes district osnabrück',
             ' making sense social impact bonds companies',
             ' deploying pay success model help address opioid epidemic united states opportunity state local action',
             ' qualitative evaluation dwp innovation fund final report',
             ' youth connect social benefit bond',
             ' combat homelessness austin nonprofit looks outside investors',
             ' social innovation fund',
             ' benin impact evaluation',
             ' india impact evaluation',
             ' big issue invest outcomes fund begins homeless vulnerable',
             ' minister health announces social impact bond heart stroke health',
             ' understanding social impact bonds',
             ' kenya impact evaluation',
             'the social impact contract is "a tool to be used with great delicacy"',
             ' social impact bond colour kitchen',
             ' illinois announces pay success initiative dually involved youth',
             ' project appraisal document proposed grant amount sdr 10 4 million us l5 0 million equivalent lao people’s democratic republic health services improvement project',
             ' takes 2 tango impact bonds latin america caribbean',
             ' housing first social impact bond feasibility study mars social finance',
             'la foncière chênelet signs a social impact contract with l anah',
             ' denver supportive housing social impact bond initiative earns first ‘success payment’ project investors',
             ' rwanda impact evaluation',
             ' abn amro invests sixth impact bond',
             ' governments results based financing match yet made heaven',
             ' housing recovery fund established indianapolis',
             ' social bonds – new zealand pilot',
             'safeguarding the north at the Ministry of the Economy and Finance for contracts with a social impact',
             ' dcf discover longwood pilot social impact investing blood bank',
             ' rise result based financing education',
             ' utkrisht development impact bond solution financing maternal health',
             ' colorado expands pay success projects improve outcomes risk teens',
             ' resilient families social benefit bond sbb',
             ' £1 45million boost accommodation education employment gloucestershire',
             ' bridges ventures impact report',
             ' fresno social impact bond asthma',
             ' impact investing helps promote well effectively resource wise way means channelling private equity projects whose aim achieve positive measurable social benefit',
             ' social impact investment nordic baltic region',
             'Sitra Foundation launch first social impact bond finland',
             ' impact evaluation baseline report fertility family planning',
             ' childfund grameen impact launch pioneering sdg impact bond women’s empowerment',
             "beccar varela advises on the launch of Argentina's first social impact bond", ' new york state intensive community asset program icap hillside receives grant support pay success project juvenile justice',
             ' ‘links 4 life’ programme social impact bond finances support disadvantaged 14 19 year olds east london',
             'social impact contracts what results 2 years after their arrival in France',
             ' first social bond focus mental health',
             ' state fund new therapists aid risk youth valley',
             ' republic congo impact evaluation',
             ' salt lake county launches two pay success projects',
             ' liberia impact evaluation',
             ' sitra impact investing',
             'a first contract with a social impact in the education sector',
             ' pay success building 25 years experience low income housing tax credit',
             ' japan social impact bond gets first batch investors',
             ' early health “pay success” social impact finance scaling prenatal health care virginia',
             'The social impact bond model is being tested in Norrköping',
             ' guide impact investing',
             ' new social impact investment reduce parolee reoffending re incarceration',
             ' first social impact bond south africa shows promise addressing youth unemployment',
             ' social impact bond buzinezzclub utrecht',
             ' fair chance fund homeless young adults',
             ' armenia impact evaluation',
             ' rise social impact bonds japan',
             ' gov dewine wants double state funding ‘home visiting ’ announces pay success model increase participation',
             ' seoul implementing sib first time asia',
             'results and evaluation pilot project “title of social impact junior code academy”',
             ' teens toddlers partners vulnerable young people toddler mentor creating transformational change young person’s life',
             ' social impact bonds investors put 5 million reducing youth unemployment',
             ' ciff ubs optimus foundation launch first development impact bond education',
             'pio, together with vdab, concludes impact capital and becode the first Flemish social impact bond',
             ' mayor emanuel announces expansion pre k 2 600 chicago public school children',
             ' nff awards 870k pay success projects designed boost community health wellness employment nurse family partnership michigan pay success project',
             ' cbf quantified ventures help baltimore city try new idea pay success environmental projects',
             ' social finance awarded two contracts dwp innovation fund support 2500 vulnerable young people thames valley north west england',
             ' point time count shows slight decrease rhode islanders experiencing homelessness',
             ' charities council set social impact bond single homeless people',
             ' mproving educational opportunities children city mannheim bertelsmann stiftung',
             ' elton john aids foundation announces world first social impact bond tackle hiv',
             ' tajikistan impact evaluation',
             ' tulsa world editorial taxpayers pay programs work new model says',
             ' afghanistan impact evaluation',
             ' social impact bonds help reduce homelessness',
             ' greater london authority homeless people',
             ' cameroon impact evaluation',
             ' rise funds impact measurement spinoff development impact bond refugees andelas african talent play energy efficiency tech',
             ' rhinos come bond market species may follow',
             ' project help 120 vulnerable homeless people launched lincolnshire',
             ' norfolk offers therapy families need thanks pioneering social impact bond',
             ' social impact bond funds birmingham fostering scheme',
             'the association solidarités nouvelles face au unemployment signs a first social impact contract and launches the expressions project',
             'education will implement project against school dropout and failure',
             ' ‘pay success’ lead clean model fizzles community groups forge ahead',
             'social impact bonds 25 jobs so far',
             ' using pay success health care',
             ' £400k boost people affected substance misuse',
             ' human capital performance bonds',
             ' 63 million grants school sector reform program nepal',
             ' commissioning independent travel training',
             ' mayday trust launches innovative outcomes based homelessness programme northamptonshire',
             ' haiti impact evaluation',
             ' baker polito administration launches workforce development pay success project',
             ' fact sheet salt lake county pay success initiative',
             ' community paramedicine pay performance model grant helps ghs expand community program',
             ' los angeles county launches “just reach” supportive housing program break cycles homelessness re incarceration',
             ' colorado expands pay success projects improve outcomes risk teens',
             ' foundation grant expand state program keeps children foster care therapy helps oklahoma county parents',
             ' action glos gloucestershire homelessness project',
             ' united states state local activity snapshot',
             'social impact contracts aréli winner of the state call for projects',
             ' peterborough prison social impact bond pilot fails hit target trigger repayments',
             ' cameroon cataract development impact loan offers innovative approach prevent blindness',
             ' impact investing achieves outcomes traditional investments cannot',
             ' raft seeks investors ontario’s first social impact bond',
             'social rights commissioned a study on the feasibility of implementing a social impact bond',
             ' award d workforce partnership fund effort encourage private investment',
             ' burkina faso approximately 6 7 million men women children living less 1 25 day',
             ' germany experiments first social impact bond',
             ' development impact bond worth 11 million launched improve education quality india',
             ' san diego foundation secures 200 000 reduce recidivism',
             ' first early childhood development social impact bond launched south africa',
             ' connecticut family stability pay success project',
             "a first bond analysis of China's social effect", ' nigeria impact evaluation',
             ' senegal impact evaluation',
             ' world bank signs agreement launch new social impact bond',
             ' 14 2 million sib focuses housing young people',
             ' chile year approximately 15 thousand children spend significant periods time foster care',
             ' democratic republic congo impact evaluation',
             ' pay success transaction designed promote cost effective watershed conservation announced newark delaware',
             ' promoting early childhood development project',
             ' grameen acumen raise funding sdg bonds social firms',
             ' delaware experiments first social impact bond fund blood bank',
             ' atlanta environmental impact bond breaks public market',
             ' pay success financing',
             ' waterfield launch development impact bond',
             ' sif administrative data pilot',
             ' utkrisht impact bond',
             ' one umbrella memphis coordinates preschool funding evaluation boost quality',
             ' cuidar de quem cuida sociedade civil apoio aos cuidadores informais',
             ' contrat à impact social rentabiliser la misère',
             ' bancos aceleran el desarrollo de las finanzas sustentables',
             ' aprovado financiamento para projeto de integração social e laboral de reclusos de prisão de grândola através da agricultura',
             ' empresas de qualificação serão pagas apenas se garantirem emprego',
             ' social impact bonds help nonprofits help others',
             ' press release world’s first 10 million sanitation development impact bond launches',
             ' fmo supports first palestinian employment development impact bond dib',
             ' third south west indian ocean fisheries governance shared growth project swiofish3',
             ' le manitoba et shoppers drug mart veulent lutter ensemble contre le tabagisme',
             ' la vivriére reclaiming nutritious home grown grains senegal',
             ' foodlink receives nearly 1m state funding',
             ' fourth partner energy gets funding power@1 prog via grameen impact’s 1st clean energy bond',
             ' afdb announces 10 billion response facility support fight covid 19 africa',
             ' afdb debuts london stock exchange largest ever green bond',
             ' afdb lists 3bn social bond lse',
             ' afdb fight covid 19 social bond listed london stock exchange',
             ' africa afdb lists us 3 billion social bond lse',
             ' african development bank celebrates milestone first social bond listing london stock',
             ' african development bank ratchets covid relief 10 billion commitmen',
             ' african development bank usd 3 bn social bond listed london stock exchange',
             ' atmah programme increase employment opportunities people determination abu dhabi',
             ' bank nova scotia scotiabank releases 2019 environment social governance report',
             ' covid 19 crisis afdb celebrates milestone first social bond listing london stock',
             ' covid 19 afdb lists largest social bond london stock exchange',
             ' goldman sachs sees rise “s” esg investing',
             ' govt considering pandemic responses including r100 billion social bond',
             ' homelessness social impact bonds united states',
             ' donate uae charities helping affected covid 19',
             ' mobilize global testing effort pay success',
             ' impact british education india',
             ' depth review change social impact bond',
             ' iowa soy farmers paid sustainable soil water outcomes',
             ' largest social bond fight covid 19 afdb launched lse',
             ' malawi gvt development bond general information supplement',
             ' new uae initiative help low income coronavirus affected families',
             ' outlook 2020 meet woman behind fallin wins',
             ' peterborough social impact bond reduces reoffending 8 4',
             ' sa considers pandemic responses including 5 3 bn social bond',
             ' social bonds response covid 19 crisis guide issuers',
             ' social bonds response covid 19 crisis guide issuers',
             ' south africa considers pandemic responses including 5 3 billion social bond',
             ' brief cdfis action african development bank 10 billion plan home medical exams',
             ' video gcc first social impact bond',
             ' west africa wamu releases handbook green bond issues',
             ' impact investing helps promote well effectively resource wise way means channelling private equity projects whose aim achieve positive measurable social benefit',
             ' catch22 developing world’s first gangs social impact bond sib',
             ' youth engagement fund sibs',
             ' jaar social impact bonds nederland',
             ' erstmals finanzieren private soziale leistungen vor',
             ' louisiana environmental impact bond may reduce coastal land loss',
             ' aspire social impact bond',
             ' contrats à impact social signature d’un protocole d’engagement avec « passeport avenir » pour lutter contre le décrochage scolaire dans l enseignement agricole',
             ' government health insurance people poverty line india quasi experimental evaluation insurance health outcomes',
             ' social impact contract tool treated gently',
             ' social impact finance bonds help asia’s ‘missing middle’ women',
             ' social impact contract aréli winner call projects summer',
             ' idea social investment lead clean cleveland advances 10 000 homes 10 years',
             ' first social impact contract education sector',
             ' social impact contract tool treated gently',
             ' foncière chênelet signs social impact contract anah',
             ' safeguarding north ministry economy finance social impact contracts',
             ' beccar varela advises launch first social impact bond argentina',
             ' social impact database',
             ' pandemic spurs investor interest social bonds',
             ' behavioral health payer based strategy improving access quality covid 19 beyond',
             ' bonds deliver 562m boost build social housing vulnerable australians',
             ' blended finance post covid19 world',
             ' performance based contracting']

relevancia = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
              1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
              0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
              1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


def cria_data_frame(data_json):

    df = pd.DataFrame(data=data_json)

    return df
# ..............................................................................


def cleanup(text):
    import string
    # Note que os sinais [] são delimitadores de um conjunto.
    punctuation = '[\/!-.:?;]'
    pattern = re.compile(punctuation)
    text_subbed = re.sub(pattern, ' ',
                         text)
    return text_subbed
# ..............................................................................


def toSingleLanguage(string):

    manchete_min = string.lower()  # tudo vira lower case

    try:
        hi_blob = textblob(manchete_min)
        manchete_pronta = hi_blob.translate(to='en')  # traduz para o inglês
    except:
        manchete_pronta = manchete_min  # caso já seja inglês, não faz nada

    return manchete_pronta
# ..............................................................................


def removeStopWords(text):

    # cria um dicionario de stop words
    sw = ["ourselves", "hers", "between", "yourself", "but", "again", "there",
          "about", "once", "during", "out", "very", "having", "with", "they",
          "own", "an", "be", "some", "for", "do", "its", "yours", "such",
          "into", "of", "most", "itself", "other", "off", "is", "s", "am",
          "or", "who", "as", "from", "him", "each", "the", "themselves",
          "until", "below", "are", "we", "these", "your", "his", "through",
          "don", "nor", "me", "were", "her", "more", "himself", "this", "down",
          "should", "our", "their", "while", "above", "both", "up", "to", "ours",
          "had", "she", "all", "no", "when", "at", "any", "before", "them",
          "same", "and", "been", "have", "in", "will", "on", "does", "yourselves",
          "then", "that", "because", "what", "over", "why", "so", "can", "did",
          "not", "now", "under", "he", "you", "herself", "has", "just", "where",
          "too", "only", "myself", "which", "those", "i", "after", "few", "whom",
          "t", "being", "if", "theirs", "my", "against", "a", "by", "doing",
          "it", "how", "further", "was", "here", "than"]

    final = ""

    # separa as palavras
    res = text.split()

    # percorre cada palavra
    for word in res:

        if word in sw:  # se for stop word
            pass
        else:  # se não for stop word
            final += " " + word

    return final
# ..............................................................................


def deepClean(manchete):

    zero = removeStopWords(manchete)  # remove stopWords
    first = cleanup(zero)  # retira pontuação
    second = toSingleLanguage(first)  # unifica a linguagem

    return second
# ..............................................................................


def cria_prop(df):

    df["Manchetes"] = df["Manchetes"].apply(
        lambda x: deepClean(x))  # faz limpeza no data_set

    return df
# ..............................................................................


def treina_modelo(arquivo_pronto, count_vect):

    # pega toda a coluna de manchetes
    X_para_treinar = arquivo_pronto.loc[:, "Manchete"]

    # pega toda a coluna de relevância
    Y_para_treinar = arquivo_pronto.loc[:, "Relevância"]

    X_train_counts = count_vect.fit_transform(X_para_treinar).toarray()  # vetoriza os dados

    #X_train, X_test, y_train, y_test = train_test_split(X_train_counts, Y_para_treinar, test_size=0.33, random_state=42)

    # Aplicando o modelo SVM (Support Vector Machine)
    model = svm.SVC(kernel='linear')  # Kernel

    # Dando fit no modelo SVM usando o dataset de treino
    model.fit(X_train_counts, Y_para_treinar)

    #predict = model.predict(X_test)  # classifica as manchetes

    #tn, fp, fn, tp = confusion_matrix(predict, y_test).ravel()

    return model
# ..............................................................................


def prev(model, dataset_para_prever, count_vect):
    
    X = dataset_para_prever["Manchetes"].tolist()  # pega todas as manchetes

    lista_string = []

    for value in X:
        lista_string.append(str(value))


    pred = count_vect.transform(lista_string).toarray()  # vetoriza os textos
    predict = model.predict(pred)  # classifica as manchetes

    dataset_para_prever["Relevância"] = pd.Series(
        predict)  # atualiza a coluna de relevância

    return dataset_para_prever
# ..............................................................................


def add(manchete, link, lista):

    # cria um json
    json = {
        "manchete": manchete,
        "link": link
    }

    lista.append(json)  # adiciona o json na lista

    return lista
# ..............................................................................


def dataFrame_to_arrayJson(data):

    array = []  # array vazio para amarzenar os jsons

    array = data.apply(lambda x: add(
        x["Manchetes"], x["Links"], array), axis=1)

    return array
# ..............................................................................


def runAll(arrayJson, data_to_train):

    for_train = data_to_train  # dataSet para treinar

    count_vect = CountVectorizer()  # cria uma instância para vetorizar

    model = treina_modelo(for_train, count_vect)  # treina o modelo

    dataFrame = cria_data_frame(arrayJson)  # cria um dataFrame com os dados

    data_frame_limpo = cria_prop(dataFrame)  # cria o dataFrame preparado

    # preve os dados de input
    data_final = prev(model, data_frame_limpo, count_vect)

    # filtra somente os relevantes
    resposta = data_final.loc[data_final["Relevância"] == 1]

    if (resposta.shape[0] == 0):

        return "false"

    else:
        formated = dataFrame_to_arrayJson(resposta).tolist()[
            0]  # formata para ser um arrayJson

        return formated
# ..............................................................................


manchetes_para_classificar = js.loads(sys.argv[1])

data = {
    "Manchete": manchetes,
    "Relevância": relevancia
}

df = pd.DataFrame(data=data)

# usa o argumento do front para filtrar dados
filtered_data = runAll(manchetes_para_classificar, df)

print(str(filtered_data))

sys.stdout.flush()
